services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /app
    volumes:
      - ./app:/app
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9001:8000"
    command: >
      sh -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && php-fpm"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app.:/app
    ports:
      - "80:80"
    depends_on:
      - php

volumes:
  app:
    driver: local
